### ISSUE TITLE
Pinning

### ISSUE THREAD

**Issue by freuk** [mpickering/haskell-indexer-nix#1]
Could you please provide nixpkgs version pinning for this? I'd like to try but had no luck with unstable, 1803, 1809. Or just give a revision :). Thank you.

**Comment by mpickering** [comment]
Perhaps, but this also requires a patch to GHC which will take quite a while to build. I could look at setting up cachix tomorrow.

**Comment by mpickering** [comment]
I pinned it and I am uploading the closure to cachix (which you can use by saying `cachix use mpickering`).

**Comment by freuk** [comment]
Thank you.
